name: Build and Publish OpenMRS
on:
  push:
    branches:
      - main
      - fhir2
    paths:
      - "bahmni-emr/**"
      - ".github/workflows/build_publish_openmrs.yml"

  repository_dispatch:
    types: ["clinic-config-trigger","hip-module-trigger"]

jobs:
  docker-build-publish:
    name: Docker Build & Publish openmrs
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: bahmni-emr/package/helm/
    steps:
      - uses: actions/checkout@v2
      - name: Download clinic_config.zip
        run: sh .github/download_artifact.sh clinic-config ClinicConfig ${{secrets.BAHMNI_PAT}} bahmni-emr
      - name: Setting Artifact version
        run: |
            APP_VERSION=$(cat bahmni-emr/.appversion)
            echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bahmni-emr/package/docker/Dockerfile
          push: true
          tags: bahmniindiadistro/bahmni-openmrs:fhir2
